# Copyright_License {
#
#  G-Meter INU.
#  Copyright (C) 2013-2014 Peter F Bradshaw
#  A detailed list of copyright holders can be found in the file "AUTHORS".
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#}

import os

topdir = '../'
topsrcdir = topdir + 'jni/'

env     = Environment(ENV = os.environ)
verbose = ARGUMENTS.get('verbose', 'n')
debug   = ARGUMENTS.get('debug', 'y')

env.Append(CXXFLAGS = '-std=gnu++11')

if verbose == 'n':
    env['CXXCOMSTR']  = 'Compiling $TARGET'
    env['CCCOMSTR']   = 'Compiling $TARGET'
    env['LINKCOMSTR'] = 'Linking $TARGET'
    env['ARCOMSTR']   = 'Archiving $TARGET'
    env['CPPCOMSTR']  = 'Processing $TARGET'
    env['PERLCOMSTR'] = 'Generating $TARGET'

githash = os.popen('git rev-parse --short --verify HEAD 2>/dev/null').read()
version = os.popen('cat ' + topdir + 'VERSION.txt').read()

env.SharedLibrary('g_meter', ['Engine/INU/INUKalman.cpp',
                              'Engine/INU/Inu.cpp',
                              'Engine/Kalman/kstatics.cpp'])

