/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

const int acc_off_x = 349;
const int acc_off_y = -6;
const int acc_off_z = 1597;
const float acc_scale_x = 16283.836110;
const float acc_scale_y = 16601.879690;
const float acc_scale_z = 16559.907794;


const int magn_off_x = 130;
const int magn_off_y = -22;
const int magn_off_z = -93;
const float magn_scale_x = 605.008602;
const float magn_scale_y = 580.995576;
const float magn_scale_z = 549.364264;
